/*
 * Created by Arpit Thool on 2021.10.15
 * Copyright © 2021 Arpit Thool. All rights reserved.
 */
package edu.vt.EntityBeans;
import edu.vt.EntityBeans.User;
import edu.vt.FacadeBeans.AbstractFacade;

import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.IOException;
import java.io.Serializable;
import java.util.Date;

/*
The @Entity annotation designates this class as a JPA Entity POJO class
representing the UserPhoto table in the TravelDiaryPlannerDB database.
 */
@Entity

// Name of the database table represented
@Table(name = "TravelNote")

@NamedQueries({
    /*
    private User userId;    --> userId is the object reference of the User object.
    userId.id               --> User object's database primary key
     */
        @NamedQuery(name = "TravelNote.findTravelNotesByUserDatabasePrimaryKey", query = "SELECT n FROM TravelNote n WHERE n.userId = :userId")
        , @NamedQuery(name = "TravelNote.findById", query = "SELECT n FROM TravelNote n WHERE n.id = :id")
})
public class TravelNote implements Serializable {
  /*
    ========================================================
      Instance variables representing the attributes (columns)
      of the User table in the TravelDiaryPlannerDB database.


    CREATE TABLE TravelNote
    (
        id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
        title VARCHAR(256) NOT NULL,
        text VARCHAR(10000) NOT NULL,
        user_id INT UNSIGNED,
        date_created DATE NOT NULL,
        lat FLOAT( 10, 8 ) NOT NULL,
        lng FLOAT( 10, 8 ) NOT NULL,
        FOREIGN KEY (user_id) REFERENCES User(id) ON DELETE CASCADE
    );
    ========================================================

   */

  private static final long serialVersionUID = 1L;

  /*
    Primary Key id is auto generated by the system as an Integer value
    starting with 1 and incremented by 1, i.e., 1,2,3,...
    A deleted entity object's primary key number is not reused.
     */
  //     id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Basic(optional = false)
  @Column(name = "id")
  private Integer id;

  //     title VARCHAR(256) NOT NULL,
  @Basic(optional = false)
  @NotNull(message = "Title is required!")
  @Column(name = "title")
  @Size(min = 1, max = 200)
  private String title;

  //     text VARCHAR(10000) NOT NULL,
  @Basic(optional = false)
  @NotNull(message = "Text is required!")
  @Column(name = "text")
  @Size(min = 1, max = 10000)
  private String text;

  //     user_id INT UNSIGNED,
  @JoinColumn(name = "user_id", referencedColumnName = "id")
  @ManyToOne
  private User userId;

  //     date_created DATE NOT NULL,
  @Basic(optional = false)
  @NotNull(message = "Video publication date is required!")
  @Column(name = "date_created")
  private Date dateCreated;

  //     lat FLOAT( 10, 8 ) NOT NULL,
  @Basic(optional = false)
  @NotNull(message = "Latitude is required!")
  @Column(name = "lat")
  private float lat;

  //     lng FLOAT( 10, 8 ) NOT NULL,
  @Basic(optional = false)
  @NotNull(message = "Longitude is required!")
  @Column(name = "lng")
  private float lng;


  /*
    ===================================================================
    Class constructors for instantiating a TravelNote entity object to
    represent a row in the TravelNote table in the TravelDiaryPlannerDB database.
    ===================================================================
     */
  public TravelNote() {
  }

  // Used in handleFileUpload() method of FileUploadManager
  public TravelNote(String text, User id) {
    this.text = text;
    userId = id;
  }

  /*
    ======================================================
    Getter and Setter methods
    ======================================================
   */

  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

  public User getUserId() {
    return userId;
  }

  public void setUserId(User userId) {
    this.userId = userId;
  }

  public Date getDateCreated() {
    return dateCreated;
  }

  public void setDateCreated(Date dateCreated) {
    this.dateCreated = dateCreated;
  }

  public float getLat() {
    return lat;
  }

  public void setLat(float lat) {
    this.lat = lat;
  }

  public float getLng() {
    return lng;
  }

  public void setLng(float lng) {
    this.lng = lng;
  }

  /*
    ================================
    Instance Methods Used Internally
    ================================
     */

  // Generate and return a hash code value for the object with database primary key id
  @Override
  public int hashCode() {
    int hash = 0;
    hash += (id != null ? id.hashCode() : 0);
    return hash;
  }

  /*
   Checks if the TravelNote object identified by 'object' is the same as the TravelNote object identified by 'id'
   Parameter object = TravelNote object identified by 'object'
   Returns True if the TravelNote 'object' and 'id' are the same; otherwise, return False
   */
  @Override
  public boolean equals(Object object) {
    if (!(object instanceof TravelNote)) {
      return false;
    }
    TravelNote other = (TravelNote) object;
    return (this.id != null || other.id == null) && (this.id == null || this.id.equals(other.id));
  }

  // Return String representation of database primary key id
  @Override
  public String toString() {
    return id.toString();
  }

  public String getLatLong() {
      return Float.toString(lat) + ", "+Float.toString(lng);
  }

  public String getGoogleMapsLink() throws IOException {
    return "http://maps.google.com/maps?q="+Float.toString(lat) + ","+ Float.toString(lng);
  }
}
